version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '4000:3000'
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    env_file:
      - .env.docker
    ports:
      - '5431:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
